#设置服务的端口
server:
  port: 8772

#eureka服务注册地址(eureka server服务地址)--注意最后是/来结尾的
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8771/eureka/

#其他相关配置
spring:
  application:
    #微服务名称,可以和项目保持一致(必要--可用于服务间访问)
    name: yb-eureka-client-query
  datasource:
    #数据库相关的配置
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://192.168.2.51:5432/postgres?useSSL=false
    username: postgres
    password: root
    #Druid连接配置
    type: com.alibaba.druid.pool.DruidDataSource
#    #下面为连接池的补充设置,应用到上面所有数据源中---->这些详细配置可以省略,使用默认值
#    initialSize: 5
#    minIdle: 5
#    maxActive: 20
#    #下面为连接池的补充设置,应用到上面所有数据源中---->这些详细配置可以省略,使用默认值
#    maxWait: 60000
#    #配置间隔多久才进行一次检测，检测需要关闭的空闲连接,单位是毫秒
#    timeBetweenEvictionRunsMillis: 60000
#    #配置一个连接在池中最小生存的时间,单位是毫秒
#    minEvictableIdleTimeMillis: 300000
#    validationQuery: SELECT 1 FROM DUAL
#    testWhileIdle: true
#    testOnBorrow: false
#    testOnReturn: false
#    #配置监控统计拦截的filters,去掉后监控界面sql无法统计,'wall'用于防火墙
#    filters: stat,wall,log4j
#    logSlowSql: true
  #jpa的相关配置--使用默认的自动建表策略
  jpa:
    hibernate:
      #自动建表为更新模式
      ddl-auto: update
    #打印sql到启动日志
    show-sql: true
    #指定连接的数据库(可要可不要)
    database: postgresql
    #指定postgresql的方言配置(必要)-->这个是hibernate对应的方言(网上查的hibernate数据库方言)
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    #实测这个方言有问题(看到有人用这个方言需要些配置类)会启动报错
    #database-platform: cn.luutqf.springboot.dialect.JsonbPostgresDialect
    properties:
      hibernate:
        temp:
          #兼容SpringBoot2.X配置
          use_jdbc_metadata_defaults: false



