#设置服务的端口
server:
  port: 8771

#eureka相关配置
eureka:
  instance:
    #eureka server服务所在通过此ip加端口即可访问eureka服务(注册)状况
    hostname: localhost
  client:
    #明自己是一个eureka server
    register-with-eureka: false
    fetch-registry: false
    #和client一样指明注册的地址,只是这个由于上面的这两行配置显得特别(因为这个是eureka server)
    defaultZone: http://${eureka.instance.hostname}:${server.port}/eureka/

#微服务名称,可以和项目保持一致(必要--可用于服务间访问)
spring:
  application:
    name: yb-eureka-server