#\u8BBE\u7F6E\u670D\u52A1\u7684\u7AEF\u53E3
server:
  port: 8771

#eureka\u76F8\u5173\u914D\u7F6E
eureka:
  instance:
    #eureka server\u670D\u52A1\u6240\u5728\u901A\u8FC7\u6B64ip\u52A0\u7AEF\u53E3\u5373\u53EF\u8BBF\u95EEeureka\u670D\u52A1(\u6CE8\u518C)\u72B6\u51B5
    hostname: localhost
  client:
    #\u660E\u81EA\u5DF1\u662F\u4E00\u4E2Aeureka server
    register-with-eureka: false
    fetch-registry: false
    #
    defaultZone: http://${eureka.instance.hostname}:${server.port}/eureka/

#\u5FAE\u670D\u52A1\u540D\u79F0,\u53EF\u4EE5\u548C\u9879\u76EE\u4FDD\u6301\u4E00\u81F4(\u5FC5\u8981--\u53EF\u7528\u4E8E\u670D\u52A1\u95F4\u8BBF\u95EE)
spring:
  application:
    name: yb-eureka-server